name: Java CI/CD Pipeline
on:
 push:
   branches:
     - testm
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Set up JDK 17
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven
   - name: Decrypt GPG key
     run: |
       echo $GPG_PRIVATE_KEY | gpg --import
     env:
       GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
   - name: Build with Maven
     run: mvn clean install
   - name: Publish to Maven Central
     env:
       SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
       SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
       GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
     run: mvn clean deploy -P release --settings .github/maven-settings.xml
   - name: Verify JAR signing
     run: gpg --verify target/*.asc