name: Deploy to Maven Central
on:
 push:
   tags:
     - 'v*.*.*'  # Adjust the tag pattern to match your versioning scheme
 release:
   types: [created]  # This triggers the workflow when a release is created

jobs:
 publish:
   runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

     - name: Build and deploy to Maven Central
       run: mvn deploy -DrepositoryId=sonatype -Durl=https://mvnrepository.com/gov.cdc.lib-hl7v2-nist-validator
       env:
         SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
         SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}