name: Deploy to GitHub Packages
on:
  push:
    branches:
      - testm
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          
      - name: Publish Package - lib-hl7v2-nist
        run: mvn -B package

      - name: Publish package to github Repo
        run: mvn clean -X deploy --settings .github/workflows/mvn-settings.xml
        env:
          LIB_GITHUB_ACTOR: '${{ secrets.LIB_GITHUB_ACTOR }}'
          LIB_GITHUB_TOKEN: '${{ secrets.LIB_GITHUB_TOKEN }}'

      - name: Publish package to Maven Central
        run: mvn clean -X deploy --settings .github/workflows/mvn-settings.xml
        env:
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
