name: Deploy to GitHub Packages
on:
  push:
    branches:
      - testm
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
          
      - name: Publish Package - lib-hl7v2-nist
        run: mvn -B package

      # - name: Publish package to github Repo
      #   run: mvn clean deploy --settings .github/workflows/mvn-settings.xml
      #   env:
      #     LIB_GITHUB_ACTOR: '${{ secrets.LIB_GITHUB_ACTOR }}'
      #     LIB_GITHUB_TOKEN: '${{ secrets.LIB_GITHUB_TOKEN }}'
      - name: Configure GPG Key
        run: |
            echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import --passphrase $GPG_PASSPHRASE

      - name: Publish package to Maven Central
        run: mvn clean -X deploy --settings .github/workflows/mvn-settings.xml
        #run: gpg --list-keys
        env:
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
          GPG_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'
          GPG_PASSPHRASE: '${{ secrets.GPG_PASSPHRASE }}'
          
