name: Maven Test on Specific Branch

on:
  push:
    branches:
      - lrp4-test-arln-igamt-prof-01  # Replace with your target branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run unit tests
        run: mvn clean test
