name: Publish package on Push to main
'on':
  workflow_dispatch: null
  push:
    branches:
      - testm
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Publish Package - lib-hl7v2-nist
        run: mvn -B package
        
      - name: build with mvn 
        run: mvn clean install

      - name: deploy to github packages
        run: mvn deploy --settings /home/runner/work/lib-hl7v2-nist-validator/lib-hl7v2-nist-validator/.github/mvn-settings.xml
        #.github/mvn-settings.xml
        #/home/runner/work/lib-hl7v2-nist-validator/lib-hl7v2-nist-validator/.github/mvn-settings.xml
        
        env:
          GITHUB_TOKEN: '${{ secrets.LIB_GITHUB_TOKEN }}'
