name: Publish package on Push to main

on:
  workflow_dispatch:
  push:
    branches: ['testm']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - uses: actions/setup-java@v3.10.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Publish Package - lib-hl7v2-nist
        run: maven publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
